isoapp/iso27000/urls.py
from django.urls import path, include, re_path
from django.contrib.auth import views as admin_views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from . import views_func, views_class

urlpatterns = [
    path('iso27000/', views_func.dashboard_view, name='dashboard'),
    path('accounts/login/', views_func.login_view, name='login'),
    path('', views_func.logout_view, name='logout'),
    path('page_404/', views_func.page_404, name='page_404'),
    path('django-sb-admin/', include('django_sb_admin.urls')),
    path('iso27000/chart', views_class.CategoryChartView.as_view(), name='chart'),
    path('iso27000/categoria/', views_class.CategoryListView.as_view(), name='category'),
    path('iso27000/crear_categoria/', views_class.CategoryCreateView.as_view(), name='create_category'),
    path('iso27000/eliminar_categoria/<pk>', views_class.CategoryDeleteView.as_view(), name='delete_category'),
    path('iso27000/actualizar_categoria/<pk>', views_class.CategoryUpdateView.as_view(), name='update_category'),
    path('iso27000/documento/', views_class.DocumentListView.as_view(), name='document'),
    path('iso27000/crear_documento/', views_class.DocumentCreateView.as_view(), name='create_document'),
    path('iso27000/eliminar_documento/<pk>', views_class.DocumentDeleteView.as_view(), name='delete_document'),
    path('iso27000/actualizar_documento/<pk>', views_class.DocumentUpdateView.as_view(), name='update_document'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns+=static(settings.MEDIA_URL, document_root=settings.STATIC_MEDIA)

isoapp/isoapp/urls.py
from django.contrib import admin
from django.urls import include, path
from iso27000.views_func import index


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('iso27000.urls')),
    path('', index, name='index'),
]

isoapp/iso27000/models.py
from django.contrib.auth.models import AbstractUser, Permission, User
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
from django.db import models
from django.core.files import File
from django.urls import reverse
from decimal import Decimal


KIND_CATEGORIES = [
    ('root', 'Raiz'),
    ('view', 'Vista'),
    ('normal', 'Normal')
]
STATES = [
    ('draft', 'Borrador'),
    ('completed', 'Terminado'),
    ('review', 'Revision'),
    ('published', 'Publicado')
]
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return instance.categorie.name + '/' + filename

class Node(models.Model):
    """docstring for Node."""
    name = models.CharField('Nombre', max_length=150)
    kind = models.CharField('Clase', choices=KIND_CATEGORIES, max_length=6, default='normal')
    code = models.CharField('Codigo', max_length=15)


    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Category(Node):
    categorie = models.ForeignKey('self',blank=True, null=True, related_name="categorias",on_delete=models.PROTECT)

    class Meta:
        verbose_name = ('Categoria')
        verbose_name_plural = ('Categorias')

    def get_absolute_url(self):
        return reverse('category')

    def clean(self):
        # Don't allow draft entries to have a pub_date.
        # if self.status == 'draft' and self.pub_date is not None:
        #     raise ValidationError({'pub_date': _('Draft entries may not have a publication date.')})
        pass

    def delete(self):
        pass

    @property
    def percent_completed_category(self):
        res = 0.0
        if self.kind == 'normal':
            documents = Document.objects.filter(categorie = self)
            lst = [d.percent_completed for d in documents]
            try:
                res =  round(sum(lst)/len(lst), 2)
            except :
                pass
        else:
            categories = Category.objects.filter(categorie = self)
            lst = [Decimal(c.percent_completed_category) for c in categories]
            try:
                res =  round(sum(lst)/len(lst), 2)
            except :
                pass
        # print(sum(res)/len(res))
        return res


class Document(models.Model):
    """docstring for Document."""
    name = models.CharField('Name', max_length=150)
    categorie = models.ForeignKey(Category, related_name='+', on_delete= models.CASCADE)
    version = models.CharField('Version', max_length=10)
    objective = models.TextField('Objetivo', max_length=400, null=True, blank=True)
    comment = models.TextField('Observaciones', max_length=500, null=True, blank=True)
    state = models.CharField('Estado',choices=STATES, default='draft', max_length=20)
    created_by = models.ForeignKey(User, blank=True, null=True, related_name='+', on_delete=models.PROTECT)
    updated_by = models.ForeignKey(User, blank=True, null=True, related_name='+', on_delete=models.PROTECT)
    reviewed_by = models.ForeignKey(User, blank=True, null=True, related_name='+', on_delete=models.PROTECT)
    published_by = models.ForeignKey(User, blank=True, null=True, related_name='+',on_delete=models.PROTECT)
    file = models.FileField(upload_to=user_directory_path)
    percent_completed = models.DecimalField('% de Cumplimiento', max_digits=4, decimal_places=2, default=0.0)

    def get_absolute_url(self):
        return reverse('document')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Call the "real" save() method.

    def delete(self, *args, **kwargs):
        print(args, kwargs)
        # if self.file:
        #     raise ValidationError({'file': ('Can not delete record this have file ')})
        super().delete(*args, **kwargs)  # Call the "real" save() method.

    class Meta:
        verbose_name = ('Documento')
        verbose_name_plural = ('Documentos')

isoapp/iso27000/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Row, Column
from .models import Category, Document
from .models import KIND_CATEGORIES, STATES


class CategoryForm(forms.ModelForm):

    class Meta:
        model= Category
        fields = [
            'name',
            'kind',
            'code',
            'categorie',
        ]

        # labels = {'percent_completed_category': 'Cumplimiento'}

        widgets = {
            'kind': forms.Select(attrs={'class':'form-control'}),
            'categorie': forms.Select(attrs={'class':'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(args, kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('save_category', 'Guardar'))
        self.helper.add_input(Submit('cancel', 'Cancelar', css_class='btn btn-danger'))

        self.helper.layout = Layout(
            Row(
                Column('name'),
                Column('kind')
            ),
            Row(
                Column('code'),
                Column('categorie')
            ),


        )


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields= [
        'name',
        'version',
        'state',
        'categorie',
        'file'  ,
        'percent_completed',
        'objective',
        'comment'
        ]

        labels={
        'name':'Nombre',
        'version':'Version',
        'state':'Estado',
        'categorie':'Categoria',
        'file':'File',
        'percent_completed': '% de Cumplimiento',
        }

        widgets= {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'version':forms.TextInput(attrs={'class':'form-control'}),
            'state':forms.Select(attrs={'class':'form-control'}),
            'categorie':forms.Select(attrs={'class':'form-control'}),
            'objective':forms.Textarea(attrs={'class':'form-control', 'rows':'3'}),
            'comment':forms.Textarea(attrs={'class':'form-control', 'rows':'3'}),
            # 'file':forms.FileField(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('save_document', 'Guardar'))
        self.helper.add_input(Submit('cancel', 'Cancelar', css_class='btn btn-danger'))

        self.helper.layout = Layout(
            Row(
                Column('name'),
                Column('version'),
                Column('categorie'),
            ),
            Row(
            Column('state'),
            Column('percent_completed')
            ),
            Row(
                Column('objective'),
                Column('comment')
            ),
            Row(
                Column('file')
            ),

        )

isoapp/iso27000/templates/base.html
{% extends "django_sb_admin/base.html" %}
{% load static %}
{% block sb_admin_header %}<!-- Header of the page scripts or link styles -->

{% endblock sb_admin_header %}
<link href="{% static 'font-awesome/css/font-awesome.min.css'  %}" rel="stylesheet" type="text/css">
{% block sb_admin_title %}ISO 27000{% endblock sb_admin_title %}

{% block sb_admin_navbar_right %}
<!-- Navbar Search -->
<form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
  <div class="input-group">
    <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
    <div class="input-group-append">
      <button class="btn btn-primary" type="button">
        <i class="fas fa-search"></i>
      </button>
    </div>
  </div>
</form>


<!-- Navbar -->
<ul class="navbar-nav ml-auto ml-md-0">
  <!-- <li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-bell fa-fw"></i>
      <span class="badge badge-danger">9+</span>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </li> -->
  <!-- <li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-envelope fa-fw"></i>
      <span class="badge badge-danger">7</span>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </li> -->
  <li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-user-circle fa-fw"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
      <a class="dropdown-item" href="{% url "admin:index" %}"> <i class="fas fa-cog fa-fw"></i>Configuracion</a>
      <!-- <a class="dropdown-item" href="#">Activity Log</a> -->
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url "logout" %}">Logout</a>
    </div>
  </li>
</ul>

{% endblock sb_admin_navbar_right %}
{% block sb_admin_sidebar %}
<li class="nav-item active">
  <a class="nav-link" href="{% url "dashboard" %}">
    <i class="fas fa-fw fa-tachometer-alt"></i>
    <span>Dashboard</span>
  </a>
</li>
<!-- <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="{% url "category" %}" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-fw fa-folder"></i>
    <span>Categorias</span>
  </a>
  <div class="dropdown-menu" aria-labelledby="pagesDropdown">
    <h6 class="dropdown-header">Login Screens:</h6>
    <a class="dropdown-item" href="{% url "sb_admin_login" %}">Login</a>
    <a class="dropdown-item" href="{% url "sb_admin_register" %}">Register</a>
    <a class="dropdown-item" href="{% url "sb_admin_forgot_password" %}">Forgot Password</a>
    <div class="dropdown-divider"></div>
    <h6 class="dropdown-header">Other Pages:</h6>
    <a class="dropdown-item" href="{% url "sb_admin_404" %}">404 Page</a>
    <a class="dropdown-item" href="{% url "sb_admin_blank" %}">Blank Page</a>
  </div>
</li> -->
<li class="nav-item">
  <a class="nav-link" href="{% url "category" %}">
    <i class="fas fa-fw fa-folder"></i>
    <span>Categorias</span></a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url "document" %}">
    <i class="fas fa-fw fa-file"></i>
    <span>Documentos</span></a>
</li>
<!-- <li class="nav-item">
  <a class="nav-link" href="{% url "sb_admin_tables" %}">
    <i class="fas fa-fw fa-table"></i>
    <span>Tablas</span></a>
</li> -->
{% endblock sb_admin_sidebar %}
{% block sb_admin_breadcrumb %}<i class="fa fa-dashboard"></i>  <a href="{% url "dashboard" %}">ISO 27001</a>{% endblock sb_admin_breadcrumb %}
{% block sb_admin_content %} <!-- content -->{% endblock sb_admin_content %}
{% block sb_admin_copyright %}<!-- copyright -->{% endblock sb_admin_copyright %}

isoapp/iso27000/templates/base_index.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{% block sb_admin_description %}{% endblock sb_admin_description %}">
  <meta name="author" content="{% block sb_admin_author %}{% endblock %}">
  <title>{% block title %}ISO 27000{% endblock %}</title>

  <!-- Custom fonts for this template-->

  <!-- Page level plugin CSS-->
  <!-- <link href="{% static "vendor/datatables/dataTables.bootstrap4.css" %}" rel="stylesheet"> -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script> -->

  <!-- Custom styles for this template-->

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  {% block sb_admin_custom_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="{% static "css/sb-admin.css" %}" rel="stylesheet">
    <link href="{% static "css/styles.css" %}" rel="stylesheet">
    <link href="{% static "vendor/fontawesome-free/css/all.min.css"  %}" rel="stylesheet" type="text/css">
  {% endblock sb_admin_custom_css %}
</head>

<body id="page-top">

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
  <a class="navbar-brand" href="{% block sb_admin_header_url %}{% url "index" %}{% endblock sb_admin_header_url %}">{% block sb_admin_header %}ISO 27000{% endblock sb_admin_header %}</a>

  <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
  {% block sb_admin_navbar_right %}
  <!-- Navbar Search -->
  <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">

  </form>


  <!-- Navbar -->
  <ul class="navbar-nav ml-auto ml-md-0">
    <li class="nav-item dropdown no-arrow mx-1">
      <!-- <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <span class="badge badge-danger">9+</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
        <a class="dropdown-item" href="{% url "dashboard" %}">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div> -->
    </li>

    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user fa-fw"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="{% url "dashboard" %}" >Login</a>
      </div>
    </li>
  </ul>
  {% endblock sb_admin_navbar_right %}
</nav>


<div id="wrapper"><!-- wrapper -->

  <div id="content-wrapper"><!-- content wrapper -->
    <div class="container-fluid"><!-- cfluid -->
  {# <div id="page-wrapper"> #}
  {# <div class="container-fluid"> #}
      <!-- Page Heading -->

  {% block sb_admin_content %}

  {% endblock sb_admin_content %}
    </div><!-- cfluid -->
  </div><!-- content wrapper -->
  <!-- Sticky Footer -->
  <!-- <footer class="footer">
      <div  class="d-flex justify-content-center py-4">
        <span>{% block sb_admin_copyright %}Copyright © Sistema de Gestion de Seguridad de la Informacion ISO 27001 2021{% endblock sb_admin_copyright %}</span>
      </div>
  </footer> -->

</div><!-- wrapper end -->
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- jQuery -->
<script src="{% static "js/jquery.js"%}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static "js/bootstrap.min.js"%}"></script>
{% block sb_admin_custom_js %}{% endblock sb_admin_custom_js %}
<!-- Bootstrap core JavaScript-->
<script src="{% static "vendor/jquery/jquery.min.js"%}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js"%}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static "vendor/jquery-easing/jquery.easing.min.js"%}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static "vendor/chart.js/Chart.min.js"%}"></script>
<script src="{% static "vendor/datatables/jquery.dataTables.js"%}"></script>
<script src="{% static "vendor/datatables/dataTables.bootstrap4.js"%}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static "js/sb-admin.min.js"%}"></script>

<!-- Demo scripts for this page-->
<script src="{% static "js/demo/datatables-demo.js"%}"></script>
<script src="{% static "js/demo/chart-area-demo.js"%}"></script>


</body>

</html>

isoapp/iso27000/templates/categories/categories_template_confirm_delete.html
{% extends "base.html" %}
{% block sb_admin_breadcrumb_active %}<li class="breadcrumb-item active">
      Eliminar Categoria
 </li>{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}

{% if perms.iso27000.delete_category %}
  <form class="form" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirmar">
  </form>
{% else %}
  <div class="alert alert-danger" role="alert">
    No tienes los permisos suficientes para modificar este registro
  </div>
{% endif %}
{% endblock sb_admin_content %}

isoapp/iso27000/templates/categories/categories_template_create.html
{% extends "base.html" %}
{% load crispy_forms_tags%}
{% block sb_admin_breadcrumb_active %}
  <li class="breadcrumb-item active">
        Crear categoria
   </li>
{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}
{% if perms.iso27000.add_category %}
  {% crispy form%}
{% else %}
  <div class="alert alert-danger" role="alert">
    No tienes los permisos suficientes para crear registros
  </div>
{% endif %}
{% endblock sb_admin_content %}

isoapp/iso27000/templates/categories/categories_template_update.html
{% extends "base.html" %}
{% load crispy_forms_tags%}
{% block sb_admin_breadcrumb_active %}
  <li class="breadcrumb-item active">
        Actualizar categoria
   </li>
{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}
    {% if perms.iso27000.change_category %}
      {% crispy form%}
    {% else %}
      <div class="alert alert-warning" role="alert">
        No tienes los permisos suficientes para modificar este registro
      </div>
    {% endif %}
{% endblock sb_admin_content %}

isoapp/iso27000/templates/documents/document_template_create.html
{% extends "base.html" %}
{% load crispy_forms_tags%}
{% block sb_admin_breadcrumb_active %}
  <li class="breadcrumb-item active">
        Crear Documento
   </li>
{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}
  <!-- <h1>Categorias</h1> -->
  {% if perms.iso27000.add_document %}
    {% crispy form%}
  {% else %}
    <div class="alert alert-warning" role="alert">
      No tienes los permisos suficientes para agregar registro
    </div>
  {% endif %}
{% endblock sb_admin_content %}

isoapp/iso27000/templates/documents/document_template_update.html
{% extends "base.html" %}
{% load crispy_forms_tags%}
{% block sb_admin_breadcrumb_active %}
  <li class="breadcrumb-item active">
        Actualizar Documento
   </li>
{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}
  <!-- <h1>Categorias</h1> -->
    {% if perms.iso27000.change_document%}
      {% crispy form%}
    {% else %}
      <div class="alert alert-warning" role="alert">
        No tienes los permisos suficientes para modificar este registro
      </div>
    {% endif %}
{% endblock sb_admin_content %}

isoapp/iso27000/templates/documents/documents_template_confirm_delete.html
{% extends "base.html" %}
{% block sb_admin_breadcrumb_active %}<li class="breadcrumb-item active">
    Eliminar Documentos
 </li>{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}
{% if perms.iso27000.delete_document %}
  <form class="form" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.pk }}"?</p>
    <input type="submit" value="Confirmar">
  </form>
{% else %}
  <div class="alert alert-danger" role="alert">
    No tienes los permisos suficientes para eliminar este registro
  </div>
{% endif %}
{% endblock sb_admin_content %}

isoapp/iso27000/templates/documents/documents_template_list.html
{% extends "base.html" %}
{% load static %}
{% block sb_admin_header %}<!-- Header of the page scripts or link styles -->
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js" type="text/javascript"> </script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
{% endblock sb_admin_header %}
{% block sb_admin_breadcrumb_active %}<li class="breadcrumb-item active">
      Documentos
 </li>{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}
  {%include "menu_models.html"%}
  {% if perms.iso27000.view_document %}
    {% if list_documents %}
    <table class="table table-striped" id="iso27000">
      <thead class="thead-dark">
        <tr>
          <th>Nombre</th>
          <th>Categoria</th>
          <th>Version</th>
          <th>Estado</th>
          <th>Cumplimiento</th>
          <th>Observaciones</th>
          <th></th>
        </tr>
      </thead>
      <tbody >
        {% for doc in list_documents %}
        <tr >
          <td>  <a href="{% url 'download_file'}" download="{{doc.file.url}}"> <i class="fas fa-download"></i> {{ doc.name }}</a></td>
          <td>  {{doc.categorie}}</td>
          <td>  {{doc.version}}</td>
          <td>  {{doc.state}}</td>
          <td>  {{doc.percent_completed}}  %</td>
          <td>  {{doc.comment}}</td>
          <td colspan="1">
            <button type="button" class="btn" onclick="location.href='{% url 'update_document' pk=doc.pk %}'">
              <i class="fas fa-edit" aria-hidden="true" style="color: #00b4d8"></i>
            </button>
            <button type="button" class="btn" onclick="location.href='{% url 'delete_document' pk=doc.pk %}'">
              <i class="fas fa-trash-alt" aria-hidden="true"  style="color: #e63946"></i>
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>No se encontraron documentos</p>
    {% endif %}
  {% else %}
    <div class="alert alert-warning" role="alert">
      No tienes los permisos suficientes para ver registros
    </div>
  {% endif %}
{% endblock sb_admin_content %}